### ISSUE TITLE
Melhoria no alinhamento de dados de conta e agência.

### ISSUE THREAD

**Issue by jansilva** [boleto-br/boleto-pdf#2]
Olá Rafael, em primeiro lugar, parabéns pelo trabalho sua lib funciona bastante bem. Eu fiz um fork dos dois repositórios o boleto-br e boleto-pdf para tentar te ajudar e melhorar o projeto(estou iniciando no trabalho com sistema financeiro). Bom, a melhoria que percebi no alinhamento é referente ao erro da imagem a seguir.

![alinhamento](https://user-images.githubusercontent.com/641565/39905275-dacdf53e-54b2-11e8-9725-b53f4ae39633.png)

Eu acho que isso é algo na hora de alinhar no pdfkit ou CSS, essa parte manjo bem pouco então não consegui resolver..

Att,

**Comment by RafaelC457ro** [comment]
Olá @jansilva obrigado, fiz uma ajuste e subi mais um versão no npm, que pode ter resolvido seu problema. Entre em contato se for positivo ou negativo.
Att.

**Comment by jansilva** [comment]
Problema resolvido na versão boleto-pdf@0.2.3, obrigado Rafael. Final de semana darei uma olhada no projeto para entender ele e começar a contribuir. Estou há 1 ano e meio trabalhando com JS então, meio que engatinhando ainda, mas com vontade de ajudar.

**Comment by RafaelC457ro** [comment]
ok @jansilva aguardo pull requests ;)
