### ISSUE TITLE
Alinhamento no campo de informação dos beneficiários.

### ISSUE THREAD

**Issue by jansilva** [boleto-br/boleto-pdf#5]
Olá, tudo bom?

Encontrei uma outra issue de alinhamento para o campo de beneficiário. Em ambas as fichas.

![alinhamento_endereco_beneficiario](https://user-images.githubusercontent.com/641565/39942474-f81f064a-5535-11e8-89d6-324edff53d89.png)

Att,

**Comment by RafaelC457ro** [comment]
@jansilva acabei de subir uma versão boleto-pdf@0.2.4  que coloca o endereço um pouco mais para esquerda e aproveita melhor o espaço, então eu sugiro que você tente manter tudo na mesma linha o
mais condensado possível.
![uni](https://user-images.githubusercontent.com/11356651/39958323-f24df8a0-55d7-11e8-98f7-4dbd255e7d18.png)
como na imagem. Espero que resolva esse problema.

**Comment by jansilva** [comment]
Funcionando bem. Valeu!
